CPU/Dual mode groups
luxteam/jobs_test_blender pull request #109
Opened 2020-09-01 14:04 UTC by Piromancer

- PURPOSE
Add more complex tests for CPU/Dual modes

- NOTES FOR REVIEWERS
All issues from this report were noticed. We didn't skip hybrid on Ubuntu and NorthStar on NVIDIA, because we're intereseted to see the behavior of this random issue (those cases will be skipped, after this issue occurs again). Render stamp cases were marked with "Do not compare" after this run

- REPORTS
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/2601/Test_20Report/

2020-09-01 14:05 UTC, Kataderon commented on jobs/Tests/CPU_Mode/test.job-manifest.xml
> +        <argument>--render_device "{RenderDevice}"</argument>
Почему не использовать этот параметр?

2020-09-01 14:13 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +            "set_value(scene.rpr, 'render_quality', ENGINE)"
Параметры, которые указываются в манифесте группы выставляются перед каждым кейсом согласно манифесту. Эта строка бессмысленна

2020-09-01 14:14 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +        "scene": "ComplexTestUber.blend"
Почему кейсы не сгруппированы по сценам?

2020-09-01 14:16 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +            "set_value(scene.rpr, 'render_stamp', 'Radeon ProRender for Blender %b | %h | Time: %pt | Passes: %pp | Objects: %so | Lights: %sl')",
Render stamp будет одинаковый в разных прогонах? Почему кейс не помечен как "Do not compare"?

2020-09-01 14:17 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +			"bpy.context.scene.rpr.use_tile_render = True",
Зачем отступ?

2020-09-01 14:19 UTC, Kataderon commented on jobs/Tests/CPU_Mode/test.job-manifest.xml
> +    <execute command='python "{ResourcesDir}/simpleRender.py"' timeout="3600">
Почему такой таймаут? В отчёте гораздо меньше времени было потрачено на эти группы

2020-09-01 14:21 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test.job-manifest.xml
> +    <execute command='python "{CommonDir}/scripts/ImageComparator/compareByJSON.py"'>
Тут будет другой путь, когда вмерджим новую структуру

2020-09-01 14:22 UTC, Kataderon requested changes
Нужно исправить замечания выше

2020-09-01 15:14 UTC, Piromancer commented on jobs/Tests/Dual_Mode/test_cases.json
> +        "scene": "ComplexTestUber.blend"
Мне кажется не стоит логически перемешивать кейсы ради экономии незначительного количества времени. Я бы предпочел чтобы осталось как есть сейчас если честно

2020-09-01 15:14 UTC, Piromancer commented on jobs/Tests/CPU_Mode/test.job-manifest.xml
> +        <argument>--render_device "{RenderDevice}"</argument>
Логично, исправлю

2020-09-01 15:15 UTC, Piromancer commented on jobs/Tests/Dual_Mode/test_cases.json
> +            "set_value(scene.rpr, 'render_quality', ENGINE)"
Ок, я не знал. Исправлю

2020-09-01 15:15 UTC, Piromancer commented on jobs/Tests/Dual_Mode/test_cases.json
> +            "set_value(scene.rpr, 'render_stamp', 'Radeon ProRender for Blender %b | %h | Time: %pt | Passes: %pp | Objects: %so | Lights: %sl')",
Помечен

2020-09-01 15:18 UTC, Piromancer commented on jobs/Tests/CPU_Mode/test.job-manifest.xml
> +    <execute command='python "{ResourcesDir}/simpleRender.py"' timeout="3600">
Исправил. Дело в том, что в майе занимает гораздо больше времени, поставил везде одинаковое время (там не проходило)

2020-09-01 15:18 UTC, Piromancer commented on jobs/Tests/Dual_Mode/test.job-manifest.xml
> +    <execute command='python "{CommonDir}/scripts/ImageComparator/compareByJSON.py"'>
Понятно, ну тогда и поменяем

2020-09-02 08:38 UTC, Piromancer commented on jobs/Tests/Dual_Mode/test_cases.json
> +			"bpy.context.scene.rpr.use_tile_render = True",
Это похоже какой-то баг гитхаба, у меня ни в каких текстовых редакторах не отображается этот отступ

2020-09-02 08:40 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +			"bpy.context.scene.rpr.use_tile_render = True",
Потому что отступы сделаны табами

2020-09-04 12:20 UTC, Kataderon commented on jobs/Scripts/extensions/Dual_Mode.py
> +def enable_dual_mode():
Где это вызывается?

2020-09-04 12:21 UTC, Kataderon requested changes
Не все замечания устранены

2020-09-04 12:21 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +            "set_value(scene.rpr, 'render_quality', ENGINE)"
Не исправлено

2020-10-07 13:50 UTC, Kataderon requested changes
Исправь форматирование пожалуйста

2020-10-07 13:50 UTC, Kataderon commented on jobs/Tests/CPU_Mode/test_cases.json
> +			"bpy.context.scene.rpr.use_tile_render = True",
Не корректный отступ

2020-10-08 12:47 UTC, Kataderon commented on jobs/Full-Hybrid.json
> -        "Athena":"",
Почему афина убрана?

2020-10-08 12:47 UTC, Kataderon commented on jobs/Tests/CPU_Mode/test.job-manifest.xml
> +    <execute command='python "{ResourcesDir}/simpleRender.py"' timeout="3600">
Таймаут не исправлен. Он точно должен быть таким?

2020-10-08 12:47 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test.job-manifest.xml
> +    <execute command='python "{ResourcesDir}/simpleRender.py"' timeout="3600">
Тот же вопрос о таймауте

2020-10-08 12:47 UTC, Kataderon commented on jobs/Tests/Dual_Mode/test_cases.json
> +			"bpy.context.scene.rpr.use_tile_render = True",
Всё ещё не исправлен отсуп

2020-10-08 13:37 UTC, Piromancer commented on jobs/Full-Hybrid.json
> -        "Athena":"",
В кейсах афины 5 кейсов, 3 из них на гибрид. Будет возвращено, когда группа будет переработана (там должен остаться один кейс). Более того, гибрид пока отключили на викли

2020-10-08 14:29 UTC, Kataderon approved these changes

2020-10-08 14:30 UTC, merged