Make saving of test resutls more stable
luxteam/jobs_test_blender pull request #170
Opened 2020-11-13 19:32 UTC by Speedwag00n

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1890
### Purpose
* Make saving of test resutls more stable
### :octocat: Related PR'S
* jobs_test_maya: 
### Jenkins Builds
* https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/538/

2020-11-15 18:53 UTC, epozine submitted a review, later dismissed

2020-11-23 17:02 UTC, Piromancer requested changes
https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/3109/Test_20Report/FULL2/NVIDIA_GF1080TI-Windows-Cloud/Results/Blender28/Cloud/report.html
Тут вообще что-то странное с логами. Если открыть лог отрендеренного кейса, то лог пустой. Если открыть рендер лог целиком, то лог первого и второго) кейсов. Ошибки в полном логе все еще пишутся после всего остального лога, т.е. например мне не понятно к какому кейсу относится эта ошибка

----------LOGS FROM FILE renderToolErr1.log----------



 ----STEDERR---- 
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FFF0F5B7788
Module  : Northstar64.dll
Thread  : 00002554

https://rpr.cis.luxoft.com/view/RPR%20Plugins/job/RadeonProRenderBlender2.8PluginManual/3109/Test_20Report/FULL2/NVIDIA_GF1080TI-Windows-Cloud/Results/Blender28/Cloud/render_tool_logs/BL28_BCS_001.log

2020-11-24 08:47 UTC, Speedwag00n commented
Обновил ссылку на отчет в описании

2020-11-24 11:54 UTC, Piromancer approved these changes

2020-11-25 16:31 UTC, merged