Change repository makeReport to jobs_launcher makeReport
luxteam/jobs_test_blender pull request #177
Opened 2020-12-04 21:32 UTC by testpassword

### Jira Ticket
* https://adc.luxoft.com/jira/browse/STVCIS-1942
### Purpose
* Make a common `makeReport.py` script for all tests repositories.
### Effect of change
* Now repositories with autotests calls unified `makeReport.py` from jobs_launcher.
### Technical steps
- [x] Change all calls in `test.job-manifest.xml` for all tests.
- [x] Remove old script.
### Dependencies
* https://github.com/luxteam/jobs_launcher/pull/140
### Jenkins Builds
* Blender: https://rpr.cis.luxoft.com/job/DevRadeonProRenderBlender2.8PluginManual/598/

2020-12-09 11:14 UTC, Speedwag00n commented
Нужно будет убрать изменений jobs_launcher из этого ПРа и всех остальных.
jobs_launcher апдейтится через специальную джобу по тегам версий

2020-12-09 11:14 UTC, Speedwag00n submitted a review, later dismissed

2020-12-10 08:10 UTC, Piromancer requested changes
Убери, пожалуйста, изменения jobs_launcher

2020-12-10 12:09 UTC, testpassword commented
> 
> 
> Убери, пожалуйста, изменения jobs_launcher

вернул на master

2020-12-10 13:35 UTC, Piromancer commented
![image](https://user-images.githubusercontent.com/44932328/101779007-be638300-3b05-11eb-8865-39b0ba233f8f.png)
У меня до сих пор отображается diff

2020-12-10 13:39 UTC, Piromancer commented
Но я вижу, что хэш сабмодуля тот же. Очень странно

2020-12-10 13:43 UTC, Speedwag00n commented
В теории можем смерджить, а после проапдейтить jobs_launcher через джобу для этого
@Piromancer , что думаешь?

2020-12-10 14:01 UTC, Piromancer commented
Можно

2020-12-10 14:02 UTC, Piromancer approved these changes

2020-12-10 14:02 UTC, Speedwag00n approved these changes

2020-12-16 17:28 UTC, merged