Testing blender rpr export and rendering results with Core
luxteam/jobs_test_blender pull request #202
Opened 2021-02-08 12:29 UTC by Flame0n

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-2002
## PURPOSE
Add test group for rpr export. Render results and send it to local reports.
## EFFECT OF CHANGE
New extension file "RPR_Export.py"
New test group "RPR_Export"
New submodule "RprSDK"
## JENKINS BUILDS
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3754/

2021-02-10 10:20 UTC, epozine requested changes
В отчете на картинках отсутствуют текстуры также, проверь правильно ли происходит экспорт.

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/base_functions.py
> +            report['file_name'] = case['case'] + case['extension']
Для какой цели данное изменение?

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +def core_Render(case):
```suggestion
def core_render(case):
```

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    if (platform.system() == 'Windows'):
У тебя в одном месте след код стайл:
if (state):

В другом:
if state:

Выбери что-то одно

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    RPR_TOOL = os.path.abspath("run.bat").rsplit("\\", 2)[0] + "\\RadeonProRenderSDK\\RadeonProRender\\"
Мне не очень понятна привязка к run.bat, зачем именно таким образом реализовано? 
Для создания путей используй os.path.join, не забывай про unix среды.

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        RPR_TOOL += "binUbuntu18\\RprsRender64"
```suggestion
        RPR_TOOL += "binUbuntu18/RprsRender64"
```

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        RPR_TOOL += "binMacOS\\RprsRender64"
```suggestion
        RPR_TOOL += "binMacOS/RprsRender64"
```

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        RPR_TOOL += "binUbuntu18\\RprsRender64"
os.path.join опять же можно

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        RPR_TOOL += "binMacOS\\RprsRender64"
os.path.join опять же можно

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    case_rpr = WORK_DIR + "\\" + case['case'] + ".rpr"
os.path.join

2021-02-10 10:20 UTC, epozine commented on jobs/Tests/RPR_Export/test.job-manifest.xml
> +        <argument>--res_path "{ScenesDir}"/Lights</argument>
```suggestion
        <argument>--res_path "{ScenesDir}"/RPR_Export</argument>
```

2021-02-10 10:20 UTC, epozine commented on jobs/Tests/RPR_Export/test_cases.json
> +        "case": "ex1",
Название не соответствует шаблону, который мы используем
BL28_**_**_***, где звездочки это категория группы, группа и номер кейса

2021-02-10 10:20 UTC, epozine commented on jobs/Tests/RPR_Export/test_cases.json
> +            "bpy.ops.rpr.export_scene_rpr(filepath=WORK_DIR + \"\\ex1.rpr\", check_existing=True, filter_glob=\"*.rpr\", export_animation=False, export_as_single_file=False, compression='LOW', start_
на юникс не будет работать, использются \\ пути

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    case_rpr = WORK_DIR + "\\" + case['case'] + ".rpr"
```suggestion
    rpr_scene = WORK_DIR + "\\" + case['case'] + ".rpr"
```

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    case_json = WORK_DIR + "\\" + case['case'] + ".json"
```suggestion
    rpr_scene_json = WORK_DIR + "\\" + case['case'] + ".json"
```

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        process = subprocess.Popen(RPR_TOOL + " " + case_rpr + " " + case_json, stdout=subprocess.PIPE, shell=True)
Нет таймаута, нет обработки зависаний. Можешь взять просто код с jobs_test_core.
Строку лучше через .format сделай

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        render_time = (datetime.datetime.now() - start_time).total_seconds()
Так не нужно делать, у тебя у приложения rprsRender есть выходной json, где есть время рендера, бери его оттуда.

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    if os.path.exists(WORK_DIR + "\\" + case['case'] + ".png"):
Снова пути виндовые

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    if os.path.exists(WORK_DIR + "\\" + case['case'] + ".png"):
Не очень понятно зачем такая операция, ты же можешь в входящий json вписать путь нужный для картинки сразу.

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    if os.path.exists(WORK_DIR + "\\" + case['case'] + ".png"):
https://github.com/luxteam/jobs_test_core/blob/master/jobs/Scripts/simpleRender.py#L230

2021-02-10 10:20 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +        process = subprocess.Popen(RPR_TOOL + " " + case_rpr + " " + case_json, stdout=subprocess.PIPE, shell=True)
https://github.com/luxteam/jobs_test_core/blob/master/jobs/Scripts/simpleRender.py#L350

2021-02-10 12:44 UTC, Speedwag00n requested changes

2021-02-10 12:44 UTC, Speedwag00n commented on jobs/Scripts/extensions/RPR_Export.py
> +    case_rpr = WORK_DIR + "\\" + case['case'] + ".rpr"
Тут тоже нужно использовать os.path.join, как писалось выше

2021-02-10 12:44 UTC, Speedwag00n commented on jobs/Scripts/extensions/RPR_Export.py
> +    case_json = WORK_DIR + "\\" + case['case'] + ".json"
Тут тоже нужно использовать os.path.join, как писалось выше

2021-02-18 11:58 UTC, epozine commented on jobs/Scripts/extensions/RPR_Export.py
> +    RPR_TOOL = os.path.join(WORK_DIR, '..', '..', '..',
Мне кажется в данном случае строку можно не переносить

2021-02-18 11:58 UTC, epozine commented on jobs/Tests/RPR_Export/test.job-manifest.xml
> +        <argument>--res_path "{ScenesDir}"/Lights</argument>
Поправишь?

2021-02-18 11:58 UTC, epozine commented
Нужен новый прогон после внесения изменений

2021-02-18 15:46 UTC, Speedwag00n requested changes
По коду замечаний помимо тех, что сделал Андрей, у меня нет.
Нужно еще обновить билд в описании ПРа, т.к. ссылка ведет на уже удаленный билд.
Не касается этой задачи, но нужно будет придумать, как мы хотим обновлять RadeonProRenderSDK сабмодуль. Можно делать из джобы, как сейчас это работает для jobs_launcher. Может есть какой-то более подходящий способ. @epozine , что думаешь?

2021-02-18 17:33 UTC, epozine commented
> По коду замечаний помимо тех, что сделал Андрей, у меня нет.
> Нужно еще обновить билд в описании ПРа, т.к. ссылка ведет на уже удаленный билд.
> Не касается этой задачи, но нужно будет придумать, как мы хотим обновлять RadeonProRenderSDK сабмодуль. Можно делать из джобы, как сейчас это работает для jobs_launcher. Может есть какой-то более подходящий способ. @epozine , что думаешь?

Насколько я понял QA будет самостоятельно это делать руками

2021-02-18 20:35 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3872
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/3873
Я не знаю почему Tahoe не проходит рендер. Поменял пути в run.bat и run.sh до ассетов из наса

2021-03-02 23:27 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4027/ - Новый прогон со всеми ОС и движками. Tahoe не работает, но насколько я знаю группа RPR_Export будет скипаться на этом движке.

2021-03-03 19:22 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4041 - только Northstar

2021-03-05 06:10 UTC, Speedwag00n reviewed
По коду замечаний, которые точно нужно исправить, нет.
По прогону: можно не запускать гибрид движки, они не очень интересны сейчас в плане поддержки + планируется их переделка со стороны разработчиков. Тахо завалился, но ты в роде бы писал, что на Тахо эта группа будет проскипана. В целом это можно сделать прямо сейчас, пока не вмерджили

2021-03-05 06:10 UTC, Speedwag00n commented on jobs/Scripts/extensions/RPR_Export.py
> +            rpr_json_content = json.load(json_file)
Можно назвать не json_file, а case_json, например, чтобы название было более говорящим. Но это уже на вкус и цвет

2021-03-05 06:10 UTC, Speedwag00n commented on jobs/Scripts/extensions/RPR_Export.py
> +            with open(os.path.join(RPR_TOOL_DIR, case['case'] + "output.json"), 'r') as json_file_2:
Тут тоже можно в теории назвать не json_file_2, а output_json

2021-03-09 14:36 UTC, Flame0n commented
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4101/ - Прогон на Macos 
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4088/ - Прогон на всех системах с логами и скипом движков. Без понятия почему только одна сцена прошла тест, но на прогоне выше этого уже не было.

2021-03-10 15:23 UTC, Speedwag00n approved these changes

2021-03-10 15:54 UTC, epozine requested changes
1. Создай пожалуйста бейзлайны
2. Прогон, в котром ошибка не является валидным. Нужно разобраться в чем причина. Попытаться воспроизвести, мы не можем полурабочие тесты отдавать QA.

2021-03-11 22:14 UTC, Flame0n commented
Обновление бейзлайнов(ошибки на ubuntu RTX2070 связаны с тем, что на машине нет 2.91 блендера): https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4129/Test_20Report/
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4132/ - mumbai
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4131/ - goto
Ошибку на маках воспроизвести не удалось. 
https://rpr.cis.luxoft.com/job/RadeonProRenderBlender2.8PluginManual/4101/ - тесты на маке до обновления бейзлайнов

2021-03-27 13:18 UTC, epozine approved these changes

2021-03-27 13:18 UTC, merged